### PR TITLE
Add Huawei CCE hosted kubernetes driver document

### PR DESCRIPTION
**Pull request by orangedeng**
Related issue: https://github.com/rancher/docs/issues/1020

### CODE REVIEW

**Comment by loganhz** [comment]
Please add `_Available as of v2.2.0_` so that people know when these features were available.

https://github.com/rancher/docs/pull/1199/files#diff-8ad9c71b76b83c64e18dda58fa1e8c68R9

**Comment by orangedeng** [comment]
Updated

**Comment by loganhz** [comment]
LGTM

**Pull request merged**
