### PR TITLE
Adding HACluster Exercise

### PR DESCRIPTION
**Pull request by dharmendrakariya**
this will help people to bring up this type of setup

### CODE REVIEW

**Comment by davidnuzik** [comment]
Hi @dharmendrakariya thank you for the contribution. We appreciate it.
However, at this time we are trying to avoid adding specific examples like you have proposed in the documentation.
At some point later we may modify the docs so that there is a section for specific examples like this. What we can do is leave this open for now and potentially add something like this in later. Let us know if you have any questions.

**Comment by dharmendrakariya** [comment]
@davidnuzik Hi, Thanks for the response. Sure, It will be useful in near future. Looking forward to see this in example section.

**Comment by dereknola** [comment]
As K3OS is a dead project, I suggest we close this PR.

**Comment by btat** [comment]
Closing based on https://github.com/rancher/docs/pull/2854#issuecomment-1177845324

**Pull request closed without merging**
