### PR TITLE
Add documentation for using Ambassador

### PR DESCRIPTION
**Pull request by concaf**
This PR adds documentation around using Ambassador (https://www.getambassador.io/) as an ingress controller in k3s.

CC: @brucehorn @inercia

### CODE REVIEW

**Comment by brucehorn** [comment]
Thanks :-)

**Comment by davidnuzik** [comment]
Thank you for your patience. Would like @cjellick to review when he has time before we consider merging this in.

**Comment by concaf** [comment]
Hey @davidnuzik @cjellick, gentle nudge ;) Anything I can do to take this forward?

**Comment by davidnuzik** [comment]
@catherineluse can you link to your PR?

We're wanting to add a section for 3rd party content so we can make it clear what has been internally validated by QA and what has not. This is important to us for support purposes. So far we still plan to get the content in but perhaps not in this area :) The PR should provide context.

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/pull/2567

**Comment by concaf** [comment]
Hey @catherineluse @davidnuzik, do we have a path forward now that #2567 is closed? :thinking:

**Comment by cjellick** [comment]
@concaf - @davidnuzik will reach out soon. We debated this one a bit internally. In the end, we decided that third-party integrations like this would be better served outside of our documentation. The main concern is that anything in our docs is perceived as endorsed and fully supported under SLAs.

If you're interested in writing something more like a blog post on the integration, David will put you in touch with our folks who handle the blog.

**Comment by catherineluse** [comment]
Closing this pull request because it's outside the scope of the documentation

**Pull request closed without merging**
