### PR TITLE
Update table showing capabilities for Rancher managed clusters

### PR DESCRIPTION
**Pull request by catherineluse**
I have updated the table that shows capabilities for different types of Rancher managed clusters. The changes are:

- Removes the imported clusters column
- Adds new columns, one for registered EKS clusters and one for all other registered clusters

I added checkmarks assuming the capabilities for registered EKS clusters are the same as Rancher launched clusters except for deletions, and the column for all other registered clusters is the same as the capabilities for imported clusters in Rancher v2.4.

Screen Shot 2020-11-19 at 12 30 23 AM

Here is the previous table for reference:

Screen Shot 2020-11-19 at 12 38 26 AM

### CODE REVIEW

**Review by rmweir — COMMENTED** [review]
I know we had it before but can you actually manage nodes for a non-EKS registered cluster? I think it depends on how you mean manage node. I don't think you can upgrade them or anything. Maybe upgrade nodes could be another row? Some of our other cloud providers are limited too, but maybe I am not interpreting this correctly.

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/issues/2356

**Comment by catherineluse** [comment]
@deniseschannon Should the 'manage nodes' row be broken down into more detail? And should the table show that the ability to manage nodes is limited for some cluster types?

**Comment by deniseschannon** [comment]
Yes, we should probably clarify what managing nodes means and break it down.

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/issues/2356

**Pull request merged**
