### PR TITLE
Adding description of locked roles

### PR DESCRIPTION
**Pull request by nathan-jenan-rancher**

### CODE REVIEW

**Comment by sangeethah** [comment]
In the place of "_Global Admin_" should we say just "__Admin__" user?

**Comment by sangeethah** [comment]
LGTM

**Comment by MBishop17** [comment]
Say “default admin”. Use the name listed on the Users page.

**Comment by nathan-jenan-rancher** [comment]
Technically it's any user with the `Administrator` permission, I misspoke earlier.

**Comment by deniseschannon** [comment]
@MBishop17 ready for you!

**Pull request closed without merging**
