### PR TITLE
Update airgapped installation documentation to newer version of cert manager

### PR DESCRIPTION
**Pull request by wilsonge**
- Update docs to cert manager 0.15.1 (currently non-airgapped docs are using 0.15.0)
- Use the installCRDs option which allows us to skip some steps

### CODE REVIEW

**Review by rawmind0 — COMMENTED** [review]
Upgrade airgapped install docs to user newer `cert-manager` version, lgtm.

At the moment, i disagree in the use of `installCRDs=true` as recommended option for installing `cert-manager`. It could generate possible issues upgrading or reinstalling the software, to just save one extra command line. Please, take a look at the comment, https://github.com/rancher/docs/pull/2578#pullrequestreview-476689901

**Comment by wilsonge** [comment]
> At the moment, i disagree in the use of installCRDs=true as recommended option for installing cert-manager. It could generate possible issues upgrading or reinstalling the software, to just save one extra command line. Please, take a look at the comment, #2578 (review)

OK will discuss whether or not to use it there - but assume in the meantime for the purposes of this PR we need to move from `00-crds.yaml` to `cert-manager.crds.yaml` as in those docs? (as obviously 00-crds.yaml is removed in v0.15).

> Upgrade airgapped install docs to user newer cert-manager version, lgtm.

Given it's now out are you happy with me moving both to 0.16 (I haven't tested this one in the airgap yet - so will need directions from you guys if you've tested or not)

**Comment by rawmind0** [comment]
> OK will discuss whether or not to use it there - but assume in the meantime for the purposes of this PR we need to move from 00-crds.yaml to cert-manager.crds.yaml as in those docs? (as obviously 00-crds.yaml is removed in v0.15).

Obviously, it should refer to the proper crd file, v1.0.1, https://github.com/jetstack/cert-manager/releases/download/v1.0.1/cert-manager.yaml


> Given it's now out are you happy with me moving both to 0.16.1 (I haven't tested this one in the airgap yet - currently running 0.15.1 - so will need directions from you guys if you've tested or not)

We are updating/testing Rancher chart to support cert-manager v1.0.x, https://github.com/rancher/rancher/pull/29017 . Could you please move both to v1.0.1 instead of v0.16.1??

**Comment by wilsonge** [comment]
Done

**Comment by wilsonge** [comment]
@rawmind0 On testing for airgapped - v1 of cert manager doesn't work - because https://github.com/rancher/rancher/blob/master/chart/templates/issuer-letsEncrypt.yaml#L4 is checking that the version is equal to 0.x (which isn't true) therefore specifies the incorrect apiVersion of alpha1 instead of alpha2

**Comment by rawmind0** [comment]
@wilsonge thanks for the quick update on that. 

> @rawmind0 On testing for airgapped - v1 of cert manager doesn't work - because https://github.com/rancher/rancher/blob/master/chart/templates/issuer-letsEncrypt.yaml#L4 is checking that the version is equal to 0.x (which isn't true) therefore specifies the incorrect apiVersion of alpha1 instead of alpha2

I already know that Rancher installations (airgapped or not) using cert-manager v1.0.0 doesn't work at the moment. As mentioned, due to that reason, PR https://github.com/rancher/rancher/pull/29017 has been submitted to address the issue. Until PR is not merged, v1 testing should be done using PR content

**Comment by wilsonge** [comment]
Cool so this shouldn't be merged until rancher/rancher#29017 is merged and in a tagged release of the helm chart

**Review by rawmind0 — APPROVED** [review]
PR https://github.com/rancher/rancher/pull/29017 already merged

LGTM

**Comment by catherineluse** [comment]
I changed the version to v1.0.4 https://github.com/rancher/docs/commit/ec87dc9dcb794f1454d6ad8d629a2ea4a2662b9f per the discussion here https://github.com/rancher/docs/issues/2803

**Pull request merged**
