### PR TITLE
Add RKE command to show available K8s versions

### PR DESCRIPTION
**Pull request by catherineluse**
This PR is intended to address this issue:
https://github.com/rancher/docs/issues/1968

### CODE REVIEW

**Comment by catherineluse** [comment]
@superseb The link to the section about getting the supported Kubernetes versions was already on the RKE upgrades page. Are you saying that nothing needs to be added to that page?

**Comment by superseb** [comment]
The PR that updated the Upgrading section contained the necessary information to upgrade, the question is if you want the command on a page that is linked on there, or if you want the command on the page it self (which caused the "issues" mentioned above).

And the other two things were not in your PR, just pointing out something that can be fixed straight away as I just saw that (and apparently not at the time I reviewed it previously)

**Comment by catherineluse** [comment]
@superseb After thinking about it some more, I think the Kubernetes versions command seems out-of-place in the config options section because it isn't really a config option.

Therefore I have moved that section into the upgrades section and reorganized the upgrades section to make it a little bit cleaner. Please let me know if this looks OK.

**Comment by superseb** [comment]
It does look clean this way, the only "problem" I see is that we now still describe setting the kubernetes version in `cluster.yml` under config options, but the command to help you with the value for that is now under upgrades and is linked there and that feels the other way around. The other use of a similar command is under `config-options/private-registries`.

The flow that I see now is that if a new user wants to configure his/her `cluster.yml` with `kubernetes_version`, it ends up at docs root -> Config Options -> Kubernetes Version -> Upgrades -> Listing Versions. In both cases, the information needed is available. I'm fine with the current approach as this is the best user experience for configuring this.

**Comment by catherineluse** [comment]
I think that the Kubernetes upgrade information should only be included on the upgrades page, because downgrades are not supported.

I think the Config Options -> Kubernetes Version section should just say "For information on upgrading Kubernetes, refer to the upgrades section. Downgrading Kubernetes is not supported."

**Pull request merged**
