### PR TITLE
Simplify example for skipping CIS scan tests

### PR DESCRIPTION
**Pull request by catherineluse**

### CODE REVIEW

**Comment by sowmyav27** [comment]
LGTM

**Comment by BartoszKaszewczuk** [comment]
This change introduced improper `JSON` formatting and removed syntax highlighting. Its a regression and should be reverted for fixed.

**Comment by catherineluse** [comment]
fixed https://github.com/rancher/docs/commit/2831296b23f3a729ca4ebbd6ca470c717f573cd8

**Comment by BartoszKaszewczuk** [comment]
Looks good now, Thanks!

**Pull request merged**
