### PR TITLE
EIO-257: doc updates for eks iam permissions

### PR DESCRIPTION
**Pull request by paraglade**
resolves https://github.com/rancherlabs/eio/issues/257

### CODE REVIEW

**Comment by catherineluse** [comment]
related issue https://github.com/rancher/docs/issues/2688

**Comment by cloudnautique** [comment]
This looks good, I like how we broke out the different permissions based on capabilities.

**Review by cloudnautique — APPROVED** [review]
LGTM

**Review by catherineluse — APPROVED** [review]
LGTM

**Pull request merged**
