### PR TITLE
Minor correction of k3s HA embedded DB notes

### PR DESCRIPTION
**Pull request by nlucansk**
Adding a small update to the notes.

image

### CODE REVIEW

**Comment by brandond** [comment]
These are supposed to be commands that users can copy-paste directly into their shell with as few modifications as possible. If you put a $ at the beginning of the line then users have to be sure not to copy that into their shell or they will get errors. What is the intent in adding that?

**Comment by nlucansk** [comment]
> These are supposed to be commands that users can copy-paste directly into their shell with as few modifications as possible. If you put a $ at the beginning of the line then users have to be sure not to copy that into their shell or they will get errors. What is the intent in adding that?

I was trying to sync the style of "double check" section.
But sure I will add a copy / paste modification in a few moments

**Comment by brandond** [comment]
Yeah, we could probably be more consistent about showing where we're providing sample output of a command (as in your `kubectl get nodes` block) and where we we are providing script blocks that we intend people to copy-paste into their shell.

**Comment by nlucansk** [comment]
> Yeah, we could probably be more consistent about showing where we're providing sample output of a command (as in your `kubectl get nodes` block) and where we we are providing commands that we intend people to copy-paste into their shell. Its possible we could use different formatters for the markdown blocks? on GH at least `bash` can be used for commands, while `console` is good for example CLI input + output.

I am 🤔  about collapsible output.
It can be also implemented for the other docs. Experienced user can just roll across the docs and do the thing.
Newcomer can read the docs line by line and use the outputs to compare results.

image

**Review by brandond — APPROVED** [review]

**Pull request merged**
