### PR TITLE
Update content/rancher/v2.6/en/logging/_index.md

### PR DESCRIPTION
**Pull request by VltraHeaven**
- Included troubleshooting steps covering Logging V1 uninstallation after upgrading to Rancher v2.6.x

### CODE REVIEW

**Comment by jtravee** [comment]
Hi @VltraHeaven, please rebase your PR on the most recent version of the staging branch (to avoid adding in all of these inapplicable commits). You can then force push to your branch `VltraHeaven:uninstall-logging-v1` to update the PR.

**Comment by VltraHeaven** [comment]
@jtravee Sorry about that. The requested rebase and force push is complete.

**Review by jtravee — CHANGES_REQUESTED** [review]

**Review by superseb — CHANGES_REQUESTED** [review]
What issue are we talking about here? `The UI changes when upgrading from Rancher v2.5 to Rancher v2.6 may cause issues` does not describe what the issue is, or what might happen. Also this sentence says it may cause issues but the title of the paragraph is `Unable to uninstall Logging V1` which implicates it cannot be uninstalled.

Without the real issue, this might confuse users. Can you describe what you ran into or a link to a filed issue where it was root caused?

**Review by superseb — CHANGES_REQUESTED** [review]
My questions are the same as previously

**Comment by VltraHeaven** [comment]
No worries. This is most likely an unnecessary PR then. Thank you for your time.

**Pull request closed without merging**
