### PR TITLE
Acme challenge verify not working

### PR DESCRIPTION
**Pull request by insekticid**
Fix for self signed certs - validation works only over http

### CODE REVIEW

**Comment by superseb** [comment]
Thanks for your contribution. Lets Encrypt is not documented and not supported in HA setup with the built in support (it will work but will have issues when it is scaled). Also, the documentation is on using NGINX as L4 using stream.

**Comment by insekticid** [comment]
I have deployed cert manager and it works well with this setup. You will not have this issue when you will use DNS01 Challenge

**Comment by superseb** [comment]
Like mentioned above, it will work, but neither adding cert-manager or using Lets Encrypt certificates is documented in this part. There will be new docs soon using Helm chart install and the possibility to use cert-manager.

**Comment by deniseschannon** [comment]
@insekticid We just moved what was in our `staging` branch into `master` as we introduced a new helm install for HA, which moved some files around. 

Sorry, you'll need to rebase as the files you referenced have moved.

**Comment by deniseschannon** [comment]
This is no longer relevant as the helm chart install has been made the standard for HA installs.

**Pull request closed without merging**
