### PR TITLE
broken links

### PR DESCRIPTION
**Pull request by diaboloshogunate**

### CODE REVIEW

**Comment by catherineluse** [comment]
I think it would be better to fix the broken links than remove them. I think those files probably moved to other places in the docs.

**Comment by diaboloshogunate** [comment]
@catherineluse agreed. Let me see which ones, I can find the updated links for.

**Comment by diaboloshogunate** [comment]
@catherineluse I cant find updated links for the following two, any idea what they should be?

`[Rancher Kubernetes Metadata]({{< baseurl >}}/rancher/v2.x/en/admin-settings/rke-metadata/)
[resource limits]({{<baseurl>}}/rancher/v2.x/en/cluster-admin/tools/istio/config/)`

**Comment by catherineluse** [comment]
The metadata one should be:

`({{<baseurl}}/rancher/v2.x/en/admin-settings/k8s-metadata)`

The Istio resource limits one should be:

`({{<baseurl>}}/rancher/v2.x/en/cluster-admin/tools/istio/resources)`

**Comment by diaboloshogunate** [comment]
Thank you, should be all set now

**Comment by catherineluse** [comment]
Looks good to me. @deniseschannon I think this PR can be merged.

**Pull request merged**
