### PR TITLE
Add rke documentaion for secrets encryption

### PR DESCRIPTION
**Pull request by moelsayed**
https://github.com/rancher/docs/issues/1832

### CODE REVIEW

**Comment by alena1108** [comment]
@catherineluse applied some minor corrections to the PR, and forwarding it to you for further editing.

One important point - this document was created for rke cli originally. But the same kind of functionality can be leveraged via Rancher UI for Rancher provisioned clusters (RKE). 

* All the modifications need to be done via editing cluster.yml 
* `Key Rotation` section has to be reworked for Rancher part https://github.com/rancher/docs/pull/1884/files#diff-93aeb367b99ac54df5b1890839cd9109R81. There is no 'rotate' action on the cluster in Rancher UI/API, so the keys can be rotated using disable/enable `secrets_encryption_config`https://github.com/rancher/docs/pull/1884/files#diff-93aeb367b99ac54df5b1890839cd9109R105


cc @deniseschannon

**Comment by catherineluse** [comment]
@alena1108 and @moelsayed , I have copy edited this section. In the last section, which is about how changing the encryption could make it hard to restore, I changed the section title to "How to Prevent Restore Failures after Rotating Keys." I also tried to add some paragraphs to spell out explicitly what you should do to prevent losing data. These are the additions:

> Therefore, we recommend that when you enable or disable encryption, or when you rotate keys, you should [create a snapshot]({{<baseurl>}}/rke/latest/en/etcd-snapshots/one-time-snapshots/) so that your backup requires the same keys that you have access to.

> This also means you should not rotate the keys during the restore process, because you would lose the encryption keys in `cluster.rkestate`.

Are these additions correct/ok?

**Comment by catherineluse** [comment]
@deniseschannon Alena reviewed these last changes. I believe this PR can be merged now.

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
