### PR TITLE
suggestion doc change

### PR DESCRIPTION
**Pull request by mjschmidt**
I wasn't able to get my nginx conf to work without adding an empty events and wrapping the whole request with http

### CODE REVIEW

**Comment by superseb** [comment]
What NGINX version was used?

**Comment by mjschmidt** [comment]
I think 1.14 I need to double check that, but I was following rancher docs when I did this.

**Comment by mjschmidt** [comment]
So those may need to be updated as well on the ha install?

**Comment by mjschmidt** [comment]
it is 1.14

**Comment by superseb** [comment]
Thanks for the report, I've made changes for both NGINX configs here https://github.com/rancher/docs/pull/1229.

Issue was that the config is made as a "vhost" config, not the main config. As the L4 example is also a full config, I've synced both locations and made them full config as well.

**Pull request closed without merging**
